Feature: GitHub Actions
      -  Coverage test
      -  Adding maven clean install

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,8 +34,27 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=akashideas2it -Dsonar.organization=akashideas2it -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
+
+      - name: Check Code Coverage
         run: |
-          ./mvnw -B verify sonar:sonar -Dsonar.projectKey=akashideas2it -Dsonar.organization=akashideas2it -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
+          coverageReport=$(cat target/site/jacoco/jacoco.xml)
+                   codeCoverage=$(parseCodeCoverageFromReport "$coverageReport")
+                   if (( $(echo "$codeCoverage < 80" | bc -l) )); then
+                     echo "Code coverage is below 80%"
+                     exit 1
+          fi
+
+          function parseCodeCoverageFromReport() {
+            report_path=target/jacoco-ut/jacoco.xml
+            if [ -f "$report_path" ]; then
+              code_coverage=$(xmllint --xpath 'string(//report/counter[@type="INSTRUCTION"]/@covered)' "$report_path")
+              echo "$code_coverage"
+            else
+              echo "Jacoco XML report not found."
+              exit 1
+            fi
+          }
           pwd
           cd target
           pwd
