Feature: GitHub Actions
      -  Coverage test
      -  Adding maven clean install

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,20 +38,19 @@ jobs:
 
       - name: Check Code Coverage
         run: |
-          coverageReport=$(cat target/site/jacoco/jacoco.xml)
-                   codeCoverage=$(parseCodeCoverageFromReport "$coverageReport")
-                   if (( $(echo "$codeCoverage < 80" | bc -l) )); then
-                     echo "Code coverage is below 80%"
-                     exit 1
-          fi
+          report_path=target/site/jacoco/jacoco.xml
 
-          function parseCodeCoverageFromReport() {
-            report_path=target/jacoco-ut/jacoco.xml
-            if [ -f "$report_path" ]; then
-              code_coverage=$(xmllint --xpath 'string(//report/counter[@type="INSTRUCTION"]/@covered)' "$report_path")
-              echo "$code_coverage"
-            else
-              echo "Jacoco XML report not found."
+          if [ -f "$report_path" ]; then
+            code_coverage=$(xmllint --xpath 'sum(//counter[@type="INSTRUCTION"]/@covered) div sum(//counter[@type="INSTRUCTION"]/@missed)' "$report_path")
+            code_coverage_percent=$(awk -v coverage="$code_coverage" 'BEGIN { printf "%.2f", coverage * 100 }')
+
+            echo "Code coverage: $code_coverage_percent%"
+
+            if (( $(echo "$code_coverage < 0.8" | bc -l) )); then
+              echo "Code coverage is below 80%"
               exit 1
             fi
-          }
+          else
+            echo "JaCoCo XML report not found."
+            exit 1
+          fi
